import type {
  Source,
  RawItem,
  Story,
  Claim,
  Evidence,
  Location,
  KnowledgeEntity,
  KnowledgeRelation,
  CitizenReport,
  Article,
  SocialContent,
  SEOMetadata,
  GEOMetadata,
  EEATScore,
  CommerceOpportunity,
  Merchant,
  User,
  AuditLog,
  JobRecord,
  PublishingJob,
  AIIonUsage,
  AgentRun,
  StoryCluster,
  VerificationRun,
  AnalyticsEvent,
  ContentPerformance,
} from '@/types';

// ============================================================
// JAKSELNEWS CONTENT FACTORY — Zod Schemas
// ============================================================

export const SourceSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(255),
  url: z.string().url(),
  type: z.enum(['rss', 'atom', 'api', 'webhook', 'manual', 'citizen']),
  category: z.enum(['government', 'media', 'social', 'official_announcement', 'citizen', 'academic', 'commercial', 'other']),
  geographic_scope: z.enum(['national', 'provincial', 'city', 'district', 'neighborhood']),
  authority_level: z.enum(['primary', 'secondary', 'unverified']),
  reliability_score: z.number().min(0).max(100).default(50),
  active: z.boolean().default(true),
  last_fetched_at: z.string().datetime().nullable(),
  last_success_at: z.string().datetime().nullable(),
  last_error: z.string().nullable(),
  metadata: z.record(z.unknown()).default({}),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<Source>;

export const RawItemSchema = z.object({
  id: z.string().uuid(),
  source_id: z.string().uuid(),
  external_id: z.string().nullable(),
  url: z.string().url().nullable(),
  canonical_url: z.string().url().nullable(),
  title: z.string().nullable(),
  raw_content: z.string(),
  published_at: z.string().datetime().nullable(),
  retrieved_at: z.string().datetime(),
  media: z.array(z.object({
    type: z.enum(['image', 'video', 'audio', 'document']),
    url: z.string().url(),
    caption: z.string().optional(),
    source: z.enum(['real', 'citizen', 'official', 'licensed', 'ai_generated']).optional(),
  })).default([]),
  metadata: z.record(z.unknown()).default({}),
  content_hash: z.string(),
  created_at: z.string().datetime(),
}) as z.ZodType<RawItem>;

export const StorySchema = z.object({
  id: z.string().uuid(),
  title: z.string().nullable(),
  summary: z.string().nullable(),
  status: z.enum(['discovered', 'investigating', 'verification_required', 'verified', 'content_ready', 'editor_review', 'approved', 'scheduled', 'published', 'rejected', 'conflicted', 'stale', 'blocked']),
  classification: z.enum(['ignore', 'monitor', 'investigate', 'draft', 'urgent_review']),
  importance_score: z.number().min(0).max(100).default(0),
  locality_score: z.number().min(0).max(100).default(0),
  novelty_score: z.number().min(0).max(100).default(0),
  urgency_score: z.number().min(0).max(100).default(0),
  risk_score: z.number().min(0).max(100).default(0),
  commercial_score: z.number().min(0).max(100).default(0),
  location_id: z.string().uuid().nullable(),
  editorial_brief: z.object({
    what_happened: z.string(),
    where: z.string(),
    when: z.string(),
    who: z.string(),
    what_is_verified: z.array(z.string()),
    what_is_uncertain: z.array(z.string()),
    why_it_matters: z.string(),
    what_residents_should_know: z.string(),
    what_happens_next: z.string(),
  }).nullable(),
  first_seen_at: z.string().datetime(),
  last_updated_at: z.string().datetime(),
  published_at: z.string().datetime().nullable(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<Story>;

export const ClaimSchema = z.object({
  id: z.string().uuid(),
  story_id: z.string().uuid(),
  claim_text: z.string().min(1),
  claim_type: z.enum(['fact', 'statement', 'event', 'prediction', 'opinion', 'rumor']),
  confidence: z.number().min(0).max(100).default(0),
  verification_status: z.enum(['unverified', 'partially_verified', 'verified', 'contradicted', 'stale', 'needs_human_review']),
  evidence_count: z.number().int().min(0).default(0),
  contradiction_count: z.number().int().min(0).default(0),
  first_observed_at: z.string().datetime(),
  last_verified_at: z.string().datetime().nullable(),
  stale_at: z.string().datetime().nullable(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<Claim>;

export const EvidenceSchema = z.object({
  id: z.string().uuid(),
  claim_id: z.string().uuid(),
  source_id: z.string().uuid(),
  raw_item_id: z.string().uuid().nullable(),
  evidence_text: z.string().min(1),
  observed_at: z.string().datetime().nullable(),
  relevance_score: z.number().min(0).max(100).default(50),
  confidence: z.number().min(0).max(100).default(50),
  created_at: z.string().datetime(),
}) as z.ZodType<Evidence>;

export const LocationSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(255),
  slug: z.string().max(255),
  type: z.enum(['country', 'province', 'city', 'district', 'neighborhood', 'landmark', 'street']),
  parent_id: z.string().uuid().nullable(),
  coordinates: z.tuple([z.number(), z.number()]).nullable(),
  metadata: z.record(z.unknown()).default({}),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<Location>;

export const ArticleSchema = z.object({
  id: z.string().uuid(),
  story_id: z.string().uuid(),
  title: z.string().min(1).max(500),
  dek: z.string().nullable(),
  summary: z.string().nullable(),
  body: z.string().nullable(),
  key_facts: z.array(z.string()).default([]),
  timeline: z.array(z.object({
    time: z.string(),
    event: z.string(),
    source: z.string().optional(),
  })).default([]),
  faq: z.array(z.object({
    question: z.string(),
    answer: z.string(),
  })).default([]),
  sources_section: z.string().nullable(),
  update_timestamp: z.string().datetime().nullable(),
  slug: z.string().max(500).nullable(),
  status: z.enum(['draft', 'version', 'published', 'archived']).default('draft'),
  version: z.number().int().min(1).default(1),
  generated_by: z.string(),
  prompt_version: z.string(),
  human_editor_id: z.string().uuid().nullable(),
  approved_by: z.string().uuid().nullable(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<Article>;

export const SEOMetadataSchema = z.object({
  id: z.string().uuid(),
  content_id: z.string().uuid(),
  content_type: z.enum(['article', 'tiktok', 'instagram_carousel', 'instagram_reel', 'youtube_short', 'x_post', 'facebook_post', 'whatsapp_status']),
  seo_title: z.string().max(70).nullable(),
  meta_description: z.string().max(160).nullable(),
  slug: z.string().max(500).nullable(),
  h1: z.string().nullable(),
  h2_list: z.array(z.string()).default([]),
  canonical: z.string().url().nullable(),
  og_title: z.string().max(95).nullable(),
  og_description: z.string().max(125).nullable(),
  og_image: z.string().url().nullable(),
  alt_texts: z.record(z.string(), z.string()).default({}),
  internal_links: z.array(z.string()).default([]),
  external_links: z.array(z.string()).default([]),
  structured_data: z.record(z.unknown()).default({}),
  keywords: z.array(z.string()).default([]),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<SEOMetadata>;

export const SocialContentSchema = z.object({
  id: z.string().uuid(),
  story_id: z.string().uuid(),
  article_id: z.string().uuid().nullable(),
  format: z.enum(['article', 'tiktok', 'instagram_carousel', 'instagram_reel', 'youtube_short', 'x_post', 'facebook_post', 'whatsapp_status']),
  hook: z.string().nullable(),
  caption: z.string().nullable(),
  body: z.string().nullable(),
  hashtags: z.array(z.string()).default([]),
  visual_direction: z.object({
    scenes: z.array(z.object({
      order: z.number(),
      start_time: z.number(),
      duration_seconds: z.number(),
      visual_type: z.enum(['image', 'video', 'infographic', 'kinetic_typography', 'map', 'ai_generated']),
      visual_source: z.enum(['real', 'citizen', 'official', 'licensed', 'ai_generated']),
      visual_description: z.string(),
      on_screen_text: z.string().nullable(),
      narration: z.string().nullable(),
      transition: z.string(),
      source_attribution: z.string().nullable(),
    })).default([]),
    total_duration_seconds: z.number(),
    style: z.string(),
  }).nullable(),
  voiceover_script: z.string().nullable(),
  subtitle: z.string().nullable(),
  thumbnail_concept: z.string().nullable(),
  cta: z.string().nullable(),
  duration_seconds: z.number().nullable(),
  source_attributions: z.array(z.string()).default([]),
  status: z.enum(['draft', 'version', 'published', 'archived']).default('draft'),
  version: z.number().int().min(1).default(1),
  generated_by: z.string(),
  prompt_version: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<SocialContent>;

export const CommerceOpportunitySchema = z.object({
  id: z.string().uuid(),
  story_id: z.string().uuid(),
  article_id: z.string().uuid().nullable(),
  opportunity_type: z.enum(['product', 'merchant', 'service', 'event', 'guide', 'affiliate', 'local_discovery']),
  relevance_score: z.number().min(0).max(100).default(0),
  commercial_type: z.enum(['affiliate', 'editorial', 'sponsored', 'local_discovery']),
  title: z.string(),
  description: z.string().nullable(),
  merchant_id: z.string().uuid().nullable(),
  products: z.array(z.object({
    name: z.string(),
    category: z.string(),
    price_range: z.string().nullable(),
    merchant_id: z.string().uuid().nullable(),
    affiliate_link: z.string().url().nullable(),
    tracking_url: z.string().url().nullable(),
    relevance_score: z.number().min(0).max(100).default(0),
  })).default([]),
  affiliate_links: z.array(z.object({
    product_name: z.string(),
    tracking_url: z.string().url(),
    provider: z.string(),
    commission_metadata: z.record(z.unknown()).nullable(),
  })).default([]),
  recommendation_strength: z.enum(['strong', 'moderate', 'weak', 'none']),
  editorial_rationale: z.string(),
  status: z.enum(['pending', 'approved', 'rejected', 'published']).default('pending'),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<CommerceOpportunity>;

export const CitizenReportSchema = z.object({
  id: z.string().uuid(),
  category: z.enum(['traffic', 'flood', 'fire', 'accident', 'public_safety', 'event', 'infrastructure', 'business', 'weather', 'other']),
  text: z.string().nullable(),
  media: z.array(z.object({
    type: z.enum(['image', 'video', 'audio', 'document']),
    url: z.string().url(),
    caption: z.string().optional(),
    source: z.enum(['real', 'citizen', 'official', 'licensed', 'ai_generated']).optional(),
  })).default([]),
  location_text: z.string().nullable(),
  location_id: z.string().uuid().nullable(),
  coordinates: z.tuple([z.number(), z.number()]).nullable(),
  submitted_at: z.string().datetime(),
  reporter_ip_hash: z.string().nullable(),
  moderation_status: z.enum(['pending', 'approved', 'rejected']).default('pending'),
  moderation_notes: z.string().nullable(),
  story_signal: z.string().uuid().nullable(),
  confidence: z.number().min(0).max(100).default(0),
  metadata: z.record(z.unknown()).default({}),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<CitizenReport>;

export const MerchantSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(255),
  location_id: z.string().uuid().nullable(),
  location_text: z.string().nullable(),
  category: z.string(),
  price_range: z.string().nullable(),
  hours: z.string().nullable(),
  website: z.string().url().nullable(),
  phone: z.string().nullable(),
  products: z.array(z.string()).default([]),
  offers: z.array(z.string()).default([]),
  affiliate_status: z.boolean().default(false),
  sponsorship_status: z.boolean().default(false),
  metadata: z.record(z.unknown()).default({}),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<Merchant>;

export const UserSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email(),
  name: z.string().min(1).max(255),
  role: z.enum(['owner', 'editor', 'moderator', 'author', 'analyst']),
  avatar_url: z.string().url().nullable(),
  is_active: z.boolean().default(true),
  last_login_at: z.string().datetime().nullable(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<User>;

export const JobRecordSchema = z.object({
  id: z.string().uuid(),
  job_type: z.string(),
  status: z.enum(['queued', 'running', 'completed', 'failed', 'retrying', 'dead_letter']),
  priority: z.number().int().default(0),
  payload: z.record(z.unknown()),
  result: z.record(z.unknown()).nullable(),
  errors: z.array(z.string()).default([]),
  attempts: z.number().int().min(0).default(0),
  max_attempts: z.number().int().min(1).default(3),
  scheduled_at: z.string().datetime().nullable(),
  started_at: z.string().datetime().nullable(),
  completed_at: z.string().datetime().nullable(),
  timeout_at: z.string().datetime().nullable(),
  idempotency_key: z.string().nullable(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
}) as z.ZodType<JobRecord>;

export const AIIonUsageSchema = z.object({
  id: z.string().uuid(),
  agent_id: z.string(),
  provider: z.string(),
  model: z.string(),
  input_tokens: z.number().int().nullable(),
  output_tokens: z.number().int().nullable(),
  estimated_cost: z.number().min(0),
  story_id: z.string().uuid().nullable(),
  content_id: z.string().uuid().nullable(),
  run_id: z.string(),
  duration_ms: z.number().int().nullable(),
  errors: z.array(z.string()).default([]),
  metadata: z.record(z.unknown()).default({}),
  created_at: z.string().datetime(),
}) as z.ZodType<AIIonUsage>;

import { z } from 'zod';
